/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Locacao;
import DAO.AluguelDAO;
import DAO.ClassificacaoDAO;
import DAO.ClienteDAO;
import DAO.Conexao;
import DAO.DVDDAO;
import DAO.FilmeDAO;
import Modelo.Aluguel;
import Modelo.Classificacao;
import Modelo.Cliente;
import Modelo.DVD;
import Modelo.Filme;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.activation.DataHandler;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Raiane
 */
public class CadastroLocacao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLocacao
     */
    public CadastroLocacao() {
        initComponents();
        AtualizaCombo();
        AtualizaDate();
        AtualizaTable();
    }
     private void AtualizaTable(){
    Connection con = Conexao.AbrirConexao();
    AluguelDAO bd = new AluguelDAO(con);
    List<Aluguel> lista = new ArrayList<>();
    lista = bd.ListarAluguel();
    DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
        while (tbm.getRowCount() >0) {            
            tbm.removeRow(0);
        }
    int i = 0;
    for(Aluguel tab : lista){
    tbm.addRow(new String[i]);
    jTable1.setValueAt(tab.getCod(), i, 0);
    jTable1.setValueAt(tab.getCoddvd(), i, 1);
    jTable1.setValueAt(tab.getCodcliente(), i, 2);
    jTable1.setValueAt(tab.getHorario(), i, 3);
    jTable1.setValueAt(tab.getData_aluguel(), i, 4);
    jTable1.setValueAt(tab.getData_devolucao(), i, 5);
    i++;
    }
    Conexao.FecharConexao(con);
    
    }
    private void AtualizaCombo(){
        Connection con = Conexao.AbrirConexao();
        ClienteDAO sql = new ClienteDAO(con);
        List<Cliente> lista = new ArrayList<>();
        lista =  sql.ListarComboCliente();
        jComboBox1.addItem("");
        
        for(Cliente f : lista){
        jComboBox1.addItem(f.getNome());
        }
        Conexao.FecharConexao(con);
    }
    public void AtualizaDate(){
    Date date = new Date();
    SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat hora = new SimpleDateFormat("hh:mm");

    hor.setText(hora.format(date));
    dataD.setText(data.format(date));

    hor.setText(hora.format(date));
    datA.setText(data.format(date));

    }
     private void InserirDados(int cod){
    Connection con = Conexao.AbrirConexao();
    DVDDAO dvd = new DVDDAO(con);
    FilmeDAO filme = new FilmeDAO(con);    
    List<DVD> listadvd = new ArrayList<>();
    List<Filme> listafilme = new ArrayList<>();
    
    
    listadvd = dvd.ListarCodFilme(cod);
    for(DVD d:listadvd){
        int codigo =d.getCod_filme();
        listafilme = filme.PesquisarCodFilme(codigo);
    }
         for (Filme f:listafilme) {
             hor.setText(f.getTitulo());
             cat.setText(""+f.getCod_categoria());             
             cl.setText(""+f.getCod_classificacao());
             jLabel10.setIcon(new ImageIcon("\\C:\\ProjetoLocadora\\imagens"+f.getCapa()+"/"));
         }
         ClassificacaoDAO cla = new ClassificacaoDAO(con);
         List<Classificacao> listacla = new ArrayList<>();
         String b = cl.getText();
         int codigo = Integer.parseInt(b);
         listacla = cla.ListarPrecoClassificacao(codigo);
         for(Classificacao c:listacla){
          String preco = c.getPreco();
          pre.setText(""+preco+"0");
         }
         Conexao.FecharConexao(con);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tit = new javax.swing.JTextField();
        cl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cli = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        datA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dataD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setText("Codigo DVD:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 90, 30);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(100, 30, 50, 30);

        jLabel2.setText("Horas:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 30, 50, 30);

        hor.setEditable(false);
        hor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horActionPerformed(evt);
            }
        });
        jPanel2.add(hor);
        hor.setBounds(410, 30, 50, 30);

        jLabel3.setText("Título");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 60, 30);

        tit.setEditable(false);
        jPanel2.add(tit);
        tit.setBounds(90, 90, 370, 30);

        cl.setEditable(false);
        cl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(cl);
        cl.setBounds(230, 150, 50, 30);

        jLabel4.setText("Classificação:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 150, 90, 30);

        jLabel5.setText("Categoria:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 30);

        cat.setEditable(false);
        cat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(cat);
        cat.setBounds(90, 150, 50, 30);

        jLabel6.setText("Valor do Aluguel:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(300, 150, 110, 30);

        pre.setEditable(false);
        pre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(pre);
        pre.setBounds(400, 150, 60, 30);

        jLabel7.setText("Cliente:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 210, 70, 30);

        cli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(cli);
        cli.setBounds(90, 210, 50, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(170, 210, 290, 30);

        jLabel8.setText("Data da Locação:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 270, 110, 30);

        datA.setEditable(false);
        datA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(datA);
        datA.setBounds(120, 270, 90, 30);

        jLabel9.setText("Data Devolução:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(230, 270, 110, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(370, 330, 90, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 330, 90, 40);

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(200, 330, 90, 40);

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(160, 30, 60, 30);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(480, 110, 290, 160);
        jPanel2.add(dataD);
        dataD.setBounds(320, 270, 90, 30);

        jTabbedPane1.addTab("Cadastrar", jPanel2);

        jPanel3.setLayout(null);

        jLabel11.setText("Pesquisar por Código:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(0, 40, 140, 30);

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(200, 40, 50, 30);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(130, 40, 50, 30);

        jLabel12.setText("Pesquisar por DVD:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(350, 20, 130, 30);
        jPanel3.add(jTextField11);
        jTextField11.setBounds(480, 20, 50, 30);

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(550, 20, 50, 30);

        jLabel13.setText("Pesquisar por Cliente:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(350, 70, 130, 30);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(480, 70, 50, 30);

        jButton7.setText("Ok");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(550, 70, 50, 30);

        jButton8.setText("Todos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(653, 50, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "DVD", "Cliente", "Horário", "Locação", "Devolução"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(3, 110, 760, 300);

        jTabbedPane1.addTab("Consultar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Connection con = Conexao.AbrirConexao();
        ClienteDAO sql = new ClienteDAO(con);
        List<Cliente> lista = new ArrayList<>();
        String nome = jComboBox1.getSelectedItem().toString();
        lista = sql.ConsultaCodigoCliente(nome);

        for(Cliente c : lista){
            int cod = c.getCodigo();
            cli.setText(""+cod);
        }
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        cl.setText("");
        cat.setText("");
        pre.setText("");
        cli.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dvd = jTextField1.getText();
        String cliente = cli.getText();
        String hora = hor.getText();
        String data_aluguel = datA.getText();
        if(dvd.equals("")||dataD.equals("")||cliente.equals("")){
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }else{

            int iddvd = Integer.parseInt(dvd);
            int idc = Integer.parseInt(cliente);
            Connection con = Conexao.AbrirConexao();
            AluguelDAO sql = new AluguelDAO(con);
            Aluguel a = new Aluguel();
            a.setCoddvd(iddvd);
            a.setCodcliente(idc);
            a.setHorario(hora);
            a.setData_aluguel(data_aluguel);

            sql.InserirAluguel(a);

            String situacao = "Emprestado";
            sql.AlterarSituacao(situacao, iddvd);

            Conexao.FecharConexao(con);
            JOptionPane.showMessageDialog(null,"Inserido com sucesso!","Video Locadora",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigo = jTextField1.getText();
        Connection con = Conexao.AbrirConexao();

        if(codigo.equals("")){
            JOptionPane.showMessageDialog(null,"Digite um código para procurar","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }else{
            DVDDAO sql = new DVDDAO(con);
            int cod = Integer.parseInt(codigo);
            if(sql.Testar_DVD(cod) == false){
                JOptionPane.showMessageDialog(null,"DVD não encontrado","Video Locadora",JOptionPane.WARNING_MESSAGE);
                Conexao.FecharConexao(con);
            }else{
                if(sql.Testarsituacao(cod)==false){
                    JOptionPane.showMessageDialog(null,"DVD de codigo ("+cod+") está indisponível","Video Locadora",JOptionPane.WARNING_MESSAGE);
                }else{
                    InserirDados(cod);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField10.getText().equals("")){
            jTextField12.setText("");
            jTextField11.setText("");
            JOptionPane.showMessageDialog(null,"Digite um código a ser procurado","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }else{
            jTextField12.setText("");
            jTextField11.setText("");
            int cod = Integer.parseInt(jTextField10.getText());

            Connection con = Conexao.AbrirConexao();
            AluguelDAO bd = new AluguelDAO(con);
            List<Aluguel> lista = new ArrayList<>();
            lista = bd.Listar_Codigo_Aluguel(cod);
            DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
            while (tbm.getRowCount() >0) {
                tbm.removeRow(0);
            }
            int i = 0;
            for(Aluguel tab : lista){
                tbm.addRow(new String[i]);
                jTable1.setValueAt(tab.getCod(), i, 0);
                jTable1.setValueAt(tab.getCoddvd(), i, 1);
                jTable1.setValueAt(tab.getCodcliente(), i, 2);
                jTable1.setValueAt(tab.getHorario(), i, 3);
                jTable1.setValueAt(tab.getData_aluguel(), i, 4);
                jTable1.setValueAt(tab.getData_devolucao(), i, 5);
            }
            hor.setText("");
            Conexao.FecharConexao(con);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(jTextField11.getText().equals("")){
            jTextField10.setText("");
            jTextField12.setText("");
            JOptionPane.showMessageDialog(null,"Digite um código a ser procurado","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }else{
            jTextField10.setText("");
            jTextField12.setText("");
            int cod = Integer.parseInt(jTextField11.getText());

            Connection con = Conexao.AbrirConexao();
            AluguelDAO bd = new AluguelDAO(con);
            List<Aluguel> lista = new ArrayList<>();
            lista = bd.Listar_Codigo_DVD(cod);
            DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
            while (tbm.getRowCount() >0) {
                tbm.removeRow(0);
            }
            int i = 0;
            for(Aluguel tab : lista){
                tbm.addRow(new String[i]);
                jTable1.setValueAt(tab.getCod(), i, 0);
                jTable1.setValueAt(tab.getCoddvd(), i, 1);
                jTable1.setValueAt(tab.getCodcliente(), i, 2);
                jTable1.setValueAt(tab.getHorario(), i, 3);
                jTable1.setValueAt(tab.getData_aluguel(), i, 4);
                jTable1.setValueAt(tab.getData_devolucao(), i, 5);
            }
            hor.setText("");
            Conexao.FecharConexao(con);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jTextField12.getText().equals("")){
            jTextField10.setText("");
            jTextField11.setText("");
            JOptionPane.showMessageDialog(null,"Digite um código a ser procurado","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }else{

            int cod = Integer.parseInt(jTextField12.getText());
            jTextField10.setText("");
            jTextField11.setText("");
            Connection con = Conexao.AbrirConexao();
            AluguelDAO bd = new AluguelDAO(con);
            List<Aluguel> lista = new ArrayList<>();
            lista = bd.Listar_Codigo_Cliente(cod);
            DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
            while (tbm.getRowCount() >0) {
                tbm.removeRow(0);
            }
            int i = 0;
            for(Aluguel tab : lista){
                tbm.addRow(new String[i]);
                jTable1.setValueAt(tab.getCod(), i, 0);
                jTable1.setValueAt(tab.getCoddvd(), i, 1);
                jTable1.setValueAt(tab.getCodcliente(), i, 2);
                jTable1.setValueAt(tab.getHorario(), i, 3);
                jTable1.setValueAt(tab.getData_aluguel(), i, 4);
                jTable1.setValueAt(tab.getData_devolucao(), i, 5);
            }
            hor.setText("");
            Conexao.FecharConexao(con);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AtualizaTable();
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cat;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField cli;
    private javax.swing.JTextField datA;
    private javax.swing.JTextField dataD;
    private javax.swing.JTextField hor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField pre;
    private javax.swing.JTextField tit;
    // End of variables declaration//GEN-END:variables
}
